name: Auto Sync from Gitee

on:
  schedule:
    - cron: '* * * * *'
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    concurrency: 
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: true
      
    steps:
      - name: Update CA certificates
        run: |
          sudo apt-get update
          sudo apt-get install -y ca-certificates
          sudo update-ca-certificates --fresh
          echo "SSL_CERT_DIR=/etc/ssl/certs" >> $GITHUB_ENV
          
      - name: Checkout GitHub repo
        uses: actions/checkout@v4
        with:
          ref: master
          fetch-depth: 0
          token: ${{ secrets.FULL_ACCESS_PAT }}

      - name: Cache node modules
        uses: actions/cache@v3
        id: npm-cache
        with:
          path: |
            node_modules
            .npm_cache
          key: ${{ runner.os }}-node-${{ hashFiles('package-lock.json') }}
          
      - name: Configure Git
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

      - name: Install dependencies
        run: |
          # 设置环境
          npm config set registry https://registry.npmmirror.com
          npm config set cafile $SSL_CERT_DIR/ca-certificates.crt
          npm cache clean --force
          
          # 安装核心依赖
          npm install -g hexo-cli --ignore-scripts
          npm install --ignore-scripts --no-optional
          
          # 单独安装问题包（使用不同策略）
          if grep -q "hexo-wordcount" package.json; then
            echo "Installing hexo-wordcount directly from npm"
            npm install hexo-wordcount@6.0.1 --registry=https://registry.npmjs.org --ignore-scripts
          fi
          
          # 验证安装
          hexo version
        env:
          NODE_OPTIONS: "--max_old_space_size=4096"
          NODE_TLS_REJECT_UNAUTHORIZED: "0"

      # ...其余步骤保持不变...