name: Auto Sync from Gitee

on:
  schedule:
    - cron: '*/5 * * * *'  # 每分钟同步一次
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: true

    steps:
      # 步骤1: 更新系统证书（可选，保留以防万一）
      - name: Update system CA certificates
        run: |
          sudo apt-get update -y
          sudo apt-get install -y ca-certificates
          sudo update-ca-certificates --fresh

      # 步骤2: 设置 Node 环境（推荐使用官方 Action）
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      # 步骤3: 检出代码
      - name: Checkout GitHub repo
        uses: actions/checkout@v4
        with:
          ref: master
          fetch-depth: 0
          token: ${{ secrets.FULL_ACCESS_PAT }}

      # 步骤4: 缓存 node_modules
      - name: Cache node modules
        uses: actions/cache@v3
        id: npm-cache
        with:
          path: |
            node_modules
            .npm_cache
          key: ${{ runner.os }}-node-${{ hashFiles('package-lock.json') }}

      # 步骤5: 配置 Git
      - name: Configure Git
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git config --global http.sslVerify true

      # 步骤6: 安装 Hexo 相关依赖（关闭 SSL 验证以规避证书过期）
      - name: Install dependencies (ignore SSL errors)
        run: |
          npm config set strict-ssl false
          npm config set registry https://registry.npmjs.org/
          npm cache clean --force

          echo "Installing hexo-cli globally..."
          npm install -g hexo-cli --ignore-scripts

          echo "Installing project dependencies..."
          if [ -f "package.json" ]; then
            jq 'del(.dependencies."hexo-wordcount")' package.json > temp.json
            mv temp.json package.json
            npm install --ignore-scripts --no-optional --legacy-peer-deps
          fi

          echo "Hexo version: $(hexo version)"

      # 步骤7: 添加 Gitee 远程仓库
      - name: Add Gitee Remote
        run: |
          git remote add gitee https://${{ secrets.GITEE_USER }}:${{ secrets.GITEE_TOKEN }}@gitee.com/zhucheng2/blog.git || true

      # 步骤8: 从 Gitee 同步代码
      - name: Sync from Gitee
        run: |
          git fetch gitee master
          git reset --hard gitee/master

      # 步骤9: 推送到 GitHub
      - name: Push to GitHub
        run: |
          git push https://${{ secrets.FULL_ACCESS_PAT }}@github.com/${{ github.repository }}.git master --force

      # 步骤10: 验证安装
      - name: Verify installation
        run: |
          echo "Installed global Hexo plugins:"
          npm list -g --depth=0 hexo-*
          echo "Project dependencies:"
          npm list --depth=0
