name: Sync from Gitee
on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout GitHub repo
        uses: actions/checkout@v4
        with:
          ref: main
          # 增量检出：仅拉取最近变更
          fetch-depth: 1  

      - name: Configure incremental sync
        run: |
          git config --global user.name "GitHub Sync Bot"
          git config --global user.email "actions@github.com"
          # 添加Gitee为远程源
          git remote add gitee https://gitee.com/zhucheng2/blog.git || true
          # 仅拉取变更文件
          git fetch gitee master --depth=1 --progress
          
      - name: Merge changes
        run: |
          # 重置到最新提交避免冲突
          git reset --hard gitee/master
          # 强制推送到GitHub（增量更新）
          git push --force-with-lease origin main
