name: Auto Sync from Gitee

on:
  schedule:
    - cron: '*/5 * * * *'  # 每5分钟同步一次
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout GitHub repo
        uses: actions/checkout@v4
        with:
          ref: master
          fetch-depth: 0
          # 使用新令牌检出
          token: ${{ secrets.FULL_ACCESS_PAT }}

      - name: Configure Git
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

      - name: Add Gitee Remote
        run: |
          git remote add gitee https://${{ secrets.GITEE_USER }}:${{ secrets.GITEE_TOKEN }}@gitee.com/zhucheng2/blog.git

      - name: Fetch Gitee Master
        run: git fetch gitee master

      - name: Reset to Gitee Master
        run: git reset --hard gitee/master

      - name: Push to GitHub
        run: |
          # 使用新令牌推送
          git push https://${{ secrets.FULL_ACCESS_PAT }}@github.com/${{ github.repository }}.git master --force