# .github/workflows/auto-sync.yml
name: Auto Sync from Gitee

on:
  schedule:
    - cron: '*/5 * * * *'  # 每5分钟同步一次
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        
      - name: Sync from Gitee
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          
          git remote add gitee https://${{ secrets.GITEE_USER }}:${{ secrets.GITEE_TOKEN }}@gitee.com/cecilzhu/blog.git
          git fetch gitee
          git reset --hard gitee/main
          git push origin main --force