name: Auto Sync from Gitee

on:
  schedule:
    - cron: '*/5 * * * *'
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout GitHub repo
        uses: actions/checkout@v4
        with:
          ref: master
          fetch-depth: 0
          token: ${{ secrets.FULL_ACCESS_PAT }}

      - name: Cache node modules
        uses: actions/cache@v3
        id: npm-cache
        with:
          path: |
            node_modules
            .npm_cache
          key: ${{ runner.os }}-node-${{ hashFiles('package-lock.json') }}
          
      - name: Configure Git
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

      - name: Install dependencies
        run: |
          npm config set registry https://registry.npmmirror.com
          npm config set strict-ssl false
          
          if [ "${{ steps.npm-cache.outputs.cache-hit }}" != "true" ]; then
            npm install -g hexo-cli --cache .npm_cache --prefer-offline
            npm install --no-optional --cache .npm_cache --prefer-offline
          fi
          
          npm config set strict-ssl true
        env:
          NODE_OPTIONS: "--max_old_space_size=4096"

      - name: Add Gitee Remote
        run: |
          git remote add gitee https://${{ secrets.GITEE_USER }}:${{ secrets.GITEE_TOKEN }}@gitee.com/zhucheng2/blog.git

      - name: Fetch Gitee Master
        run: git fetch gitee master

      - name: Reset to Gitee Master
        run: git reset --hard gitee/master

      - name: Push to GitHub
        run: |
          git push https://${{ secrets.FULL_ACCESS_PAT }}@github.com/${{ github.repository }}.git master --force