name: Sync from Gitee (triggered by API)

on:
  repository_dispatch:
    types: [gitee_sync]
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout GitHub repo
        uses: actions/checkout@v3

      - name: Sync from Gitee
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git remote add gitee https://gitee.com/zhucheng2/blog.git
          git fetch gitee master
          git reset --hard gitee/master
          git push origin main --force
